Revert "COMP:  Use C++11 ITK_NOEXCEPT directly"
This reverts commit b0ea16bc57aa4cbcd2ff252ce9ec37f2403611c0.

C++ headers were included from a C source file. This commit fixes the following error on Visual Studio 2017 version 15.8.8:

1>------ Build started: Project: VariationalRegistration, Configuration: Debug x64 ------
1>VariationalRegistrationMain.cxx
1>getopt.c
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\include\cstdio(29): error C2061: syntax error: identifier 'std'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\include\cstdio(29): error C2059: syntax error: ';'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\include\cstdio(29): error C2449: found '{' at file scope (missing function header?)
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\include\cstdio(56): error C2059: syntax error: '}'
1>c:\dev\itk-git\modules\remote\variationalregistration\src\win32_compatibility\getopt.c(123): fatal error C1004: unexpected end-of-file found
1>Done building project "VariationalRegistration.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 48 up-to-date, 0 skipped ==========